# arguments for dataset
dataset: pascal
data_root: dpt-head-trainer/data/VOC
nclass: 21
crop_size: 518

# arguments for training
epochs: 60
batch_size: 2  # per GPU x 4 GPUs
lr: 0.000005
lr_multi: 40.0
criterion:
  name: CELoss
  kwargs:
    ignore_index: 255
conf_thresh: 0.75

# arguments for model
model: dpt
backbone: dinov2_small
lock_backbone: False
heads_include_background: true

# arguments for multi-head / class groups
class_groups:
  vehicles:
    - aeroplane
    - bicycle
    - boat
    - bus
    - car
    - motorbike
    - train
  animals:
    - bird
    - cat
    - cow
    - dog
    - horse
    - sheep
  indoor:
    - bottle
    - chair
    - dining table
    - potted plant
    - sofa
    - tv/monitor

group_head_paths:
  vehicles: dpt-head-trainer/training-logs/vehicles/best_head.pth
  animals:  dpt-head-trainer/training-logs/animals/best_head.pth
  indoor:   dpt-head-trainer/training-logs/indoor/best_head.pth